# Generated by Django 5.1.4 on 2024-12-29 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0002_book1_delete_book'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book1',
            new_name='Book',
        ),
    ]
